substitutions:
  device_name: "Shelly Plus 1"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: shelly-plus-1
  platformio_options:
    board_build.f_cpu: 160000000L

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
 
  ap:
    ssid: "Garasje-Shelly Fallback Hotspot"
    password: aD6XboPT3qAP

logger:

api:
  encryption:
    key: !secret shelly1_encryption_key

ota:
  password: !secret shelly1_ota_passwd

switch:
  - platform: gpio
    pin: GPIO4
    name: "Garasjedør Rele"
    id: relay
    internal: true

binary_sensor:
  - platform: gpio
    pin: GPIO5
    name: "Garasjedør Kontakt"
    id: contact_sensor
    internal: true
    filters:
      - invert:
      # Debounce the contact sensor to prevent rapid on/off/on events
      - delayed_on_off: 500ms

cover:
  - platform: template
    device_class: garage
    name: "Garasjedør"
    id: template_cov
    lambda: |-
      if (id(contact_sensor).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay
    close_action:
      - switch.turn_on: relay
      - delay: 0.5s
      - switch.turn_off: relay

sensor:
  - platform: wifi_signal
    name: ${device_name} WiFi Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} "Uptime"
